//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Home.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP Method: ähnelt.
        /// </summary>
        public static string HttpMethode {
            get {
                return ResourceManager.GetString("HttpMethode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Concept and realization by Andreas L. ähnelt.
        /// </summary>
        public static string strAbout_Line1 {
            get {
                return ResourceManager.GetString("strAbout_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many thanks ... ähnelt.
        /// </summary>
        public static string strAbout_Line2 {
            get {
                return ResourceManager.GetString("strAbout_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... to ähnelt.
        /// </summary>
        public static string strAboutTextFluentRibbon_1 {
            get {
                return ResourceManager.GetString("strAboutTextFluentRibbon_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for the menu! ähnelt.
        /// </summary>
        public static string strAboutTextFluentRibbon_2 {
            get {
                return ResourceManager.GetString("strAboutTextFluentRibbon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... to ähnelt.
        /// </summary>
        public static string strAboutTextIcons8_1 {
            get {
                return ResourceManager.GetString("strAboutTextIcons8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for the free icons! ähnelt.
        /// </summary>
        public static string strAboutTextIcons8_2 {
            get {
                return ResourceManager.GetString("strAboutTextIcons8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Devices: {0} ähnelt.
        /// </summary>
        public static string strActiveDevicesTab {
            get {
                return ResourceManager.GetString("strActiveDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity ähnelt.
        /// </summary>
        public static string strActivity {
            get {
                return ResourceManager.GetString("strActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string strAll {
            get {
                return ResourceManager.GetString("strAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllDevices: {0} ähnelt.
        /// </summary>
        public static string strAllDevicesTab {
            get {
                return ResourceManager.GetString("strAllDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Android device cannot be shutdown or restarted! ähnelt.
        /// </summary>
        public static string strAndroidDeviceNoShutdownSupport {
            get {
                return ResourceManager.GetString("strAndroidDeviceNoShutdownSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string strApply {
            get {
                return ResourceManager.GetString("strApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sure? ähnelt.
        /// </summary>
        public static string strAreYouSure {
            get {
                return ResourceManager.GetString("strAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the device {0}? ähnelt.
        /// </summary>
        public static string strAreYouSureToDeleteDevice {
            get {
                return ResourceManager.GetString("strAreYouSureToDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery: ähnelt.
        /// </summary>
        public static string strBattery {
            get {
                return ResourceManager.GetString("strBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}% Battery left ... ähnelt.
        /// </summary>
        public static string strBatteryWarning_Message {
            get {
                return ResourceManager.GetString("strBatteryWarning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit ähnelt.
        /// </summary>
        public static string strBit {
            get {
                return ResourceManager.GetString("strBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string strCancel {
            get {
                return ResourceManager.GetString("strCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charging ähnelt.
        /// </summary>
        public static string strCharging {
            get {
                return ResourceManager.GetString("strCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Screenshots ({1}) have been cleaned up! ähnelt.
        /// </summary>
        public static string strCleanUpResultMessage {
            get {
                return ResourceManager.GetString("strCleanUpResultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear changes ähnelt.
        /// </summary>
        public static string strClearHwChanges {
            get {
                return ResourceManager.GetString("strClearHwChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Log ähnelt.
        /// </summary>
        public static string strClearLog {
            get {
                return ResourceManager.GetString("strClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device uses an outdated client version! ähnelt.
        /// </summary>
        public static string strClientVersionNotUpToDate {
            get {
                return ResourceManager.GetString("strClientVersionNotUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device uses the latest client version! ähnelt.
        /// </summary>
        public static string strClientVersionUpToDate {
            get {
                return ResourceManager.GetString("strClientVersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commands ähnelt.
        /// </summary>
        public static string strCommands {
            get {
                return ResourceManager.GetString("strCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully connected to &quot;{0}&quot;! ähnelt.
        /// </summary>
        public static string strConnectedSuccessfullyMessage {
            get {
                return ResourceManager.GetString("strConnectedSuccessfullyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cores ähnelt.
        /// </summary>
        public static string strCores {
            get {
                return ResourceManager.GetString("strCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU: ähnelt.
        /// </summary>
        public static string strCPUDescription {
            get {
                return ResourceManager.GetString("strCPUDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string strDark {
            get {
                return ResourceManager.GetString("strDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color mode: ähnelt.
        /// </summary>
        public static string strDarkModeSettingsTitle {
            get {
                return ResourceManager.GetString("strDarkModeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM/dd/yyyy ähnelt.
        /// </summary>
        public static string strDateFormat {
            get {
                return ResourceManager.GetString("strDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM/dd/yyyy HH:mm ähnelt.
        /// </summary>
        public static string strDateTimeFormat {
            get {
                return ResourceManager.GetString("strDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        public static string strDays {
            get {
                return ResourceManager.GetString("strDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        /// </summary>
        public static string strDefault {
            get {
                return ResourceManager.GetString("strDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Device ähnelt.
        /// </summary>
        public static string strDeleteDevice {
            get {
                return ResourceManager.GetString("strDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device ähnelt.
        /// </summary>
        public static string strDevice {
            get {
                return ResourceManager.GetString("strDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: {0} of {1} device(s) are active! ähnelt.
        /// </summary>
        public static string strDevice_InitalStatusMessage {
            get {
                return ResourceManager.GetString("strDevice_InitalStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ({0} Warning(s)!) ähnelt.
        /// </summary>
        public static string strDevice_InitalStatusMessage_Warnings {
            get {
                return ResourceManager.GetString("strDevice_InitalStatusMessage_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery Remaining (%) ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_Battery_Name {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_Battery_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery Remaining: {0} % ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_Battery_Tooltip {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_Battery_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU Usage (%) ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_CPU_Name {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_CPU_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU: {0} % ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_CPU_Tooltip {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_CPU_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISK Usage (%) ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_DISK_Name {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_DISK_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISK: {0} % ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_DISK_Tooltip {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_DISK_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM Usage (%) ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_RAM_Name {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_RAM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM: {0} % ähnelt.
        /// </summary>
        public static string strDeviceActivityPlot_RAM_Tooltip {
            get {
                return ResourceManager.GetString("strDeviceActivityPlot_RAM_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The unit is offline - switching to live mode is not possible! ähnelt.
        /// </summary>
        public static string strDeviceCannotSwitchToLiveMode {
            get {
                return ResourceManager.GetString("strDeviceCannotSwitchToLiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardware Protocol ähnelt.
        /// </summary>
        public static string strDeviceChanges {
            get {
                return ResourceManager.GetString("strDeviceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client-Version:  ähnelt.
        /// </summary>
        public static string strDeviceClientVersion {
            get {
                return ResourceManager.GetString("strDeviceClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description:  ähnelt.
        /// </summary>
        public static string strDeviceDescription {
            get {
                return ResourceManager.GetString("strDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not associated ähnelt.
        /// </summary>
        public static string strDeviceLocationNotAssigend {
            get {
                return ResourceManager.GetString("strDeviceLocationNotAssigend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Log ähnelt.
        /// </summary>
        public static string strDeviceLog {
            get {
                return ResourceManager.GetString("strDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This device is currently offline! No operations can be executed! ähnelt.
        /// </summary>
        public static string strDeviceOfflineCannotExecuteCommand {
            get {
                return ResourceManager.GetString("strDeviceOfflineCannotExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uptime:  ähnelt.
        /// </summary>
        public static string strDeviceOnlineTime {
            get {
                return ResourceManager.GetString("strDeviceOnlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  &quot;The device was registered successfully! ähnelt.
        /// </summary>
        public static string strDeviceRegister_Success {
            get {
                return ResourceManager.GetString("strDeviceRegister_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error retrieving the data: {0} ähnelt.
        /// </summary>
        public static string strDeviceScheduling_Settings_FailedToRecieveData {
            get {
                return ResourceManager.GetString("strDeviceScheduling_Settings_FailedToRecieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start:  ähnelt.
        /// </summary>
        public static string strDeviceStart {
            get {
                return ResourceManager.GetString("strDeviceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISKs ähnelt.
        /// </summary>
        public static string strDisk {
            get {
                return ResourceManager.GetString("strDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to restart the machine {0}? ähnelt.
        /// </summary>
        public static string strDoYouReallyWantToRestartDevice {
            get {
                return ResourceManager.GetString("strDoYouReallyWantToRestartDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to shutdown the machine {0}? ähnelt.
        /// </summary>
        public static string strDoYouReallyWantToShutdownDevice {
            get {
                return ResourceManager.GetString("strDoYouReallyWantToShutdownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to wake up the device &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string strDoYouReallyWantToWakeUpDevice {
            get {
                return ResourceManager.GetString("strDoYouReallyWantToWakeUpDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        public static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute Command ähnelt.
        /// </summary>
        public static string strExecuteCommand {
            get {
                return ResourceManager.GetString("strExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to clear device log: {0} ähnelt.
        /// </summary>
        public static string strFailedToClearDeviceLog {
            get {
                return ResourceManager.GetString("strFailedToClearDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to clear the hardware changes of this device: {0} ähnelt.
        /// </summary>
        public static string strFailedToClearedHardwareLog {
            get {
                return ResourceManager.GetString("strFailedToClearedHardwareLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to connected to &quot;{0}&quot;: {1} ähnelt.
        /// </summary>
        public static string strFailedToConnectMessage {
            get {
                return ResourceManager.GetString("strFailedToConnectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error downloading the file: ähnelt.
        /// </summary>
        public static string strFailedToDownloadFile {
            get {
                return ResourceManager.GetString("strFailedToDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while retrieving the folder: ähnelt.
        /// </summary>
        public static string strFailedToDownloadFolder {
            get {
                return ResourceManager.GetString("strFailedToDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to save the report! ähnelt.
        /// </summary>
        public static string strFailedToSaveReport {
            get {
                return ResourceManager.GetString("strFailedToSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving the image: {0} ähnelt.
        /// </summary>
        public static string strFailedToSaveScreenshotAsImage {
            get {
                return ResourceManager.GetString("strFailedToSaveScreenshotAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature is currently only supported on newer Windows systems (Windows 7 SP1 or newer) or on Linux Systems! ähnelt.
        /// </summary>
        public static string strFeatureIsNotSupportedOnSelectedDevice {
            get {
                return ResourceManager.GetString("strFeatureIsNotSupportedOnSelectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string strFile {
            get {
                return ResourceManager.GetString("strFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date Of Change ähnelt.
        /// </summary>
        public static string strFileExplorerDateOfChange {
            get {
                return ResourceManager.GetString("strFileExplorerDateOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete file ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DeleteFile {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete folder ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DeleteFolder {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download file ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DownloadFile {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download folder as ZIP-File ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DownloadFolderAsZIP {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DownloadFolderAsZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_Properties {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string strFileExplorerName {
            get {
                return ResourceManager.GetString("strFileExplorerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        public static string strFileExplorerSize {
            get {
                return ResourceManager.GetString("strFileExplorerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string strFileExplorerType {
            get {
                return ResourceManager.GetString("strFileExplorerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder ähnelt.
        /// </summary>
        public static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics: ähnelt.
        /// </summary>
        public static string strGraphicsDescription {
            get {
                return ResourceManager.GetString("strGraphicsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die free of ähnelt.
        /// </summary>
        public static string strHDD_FreeOf {
            get {
                return ResourceManager.GetString("strHDD_FreeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        public static string strHours {
            get {
                return ResourceManager.GetString("strHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTML Report File (*.html)|*.html ähnelt.
        /// </summary>
        public static string strHtmlReportFilter {
            get {
                return ResourceManager.GetString("strHtmlReportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF Report File (*.pdf)|*.pdf ähnelt.
        /// </summary>
        public static string strHtmlReportFilterPDF {
            get {
                return ResourceManager.GetString("strHtmlReportFilterPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual Overview ähnelt.
        /// </summary>
        public static string strIndividualOverview {
            get {
                return ResourceManager.GetString("strIndividualOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show accent color in titlebar ähnelt.
        /// </summary>
        public static string strIsColorfulTheme {
            get {
                return ResourceManager.GetString("strIsColorfulTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string strLang {
            get {
                return ResourceManager.GetString("strLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string strLight {
            get {
                return ResourceManager.GetString("strLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location:  ähnelt.
        /// </summary>
        public static string strLocation {
            get {
                return ResourceManager.GetString("strLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MAC Address: ähnelt.
        /// </summary>
        public static string strMacAddress {
            get {
                return ResourceManager.GetString("strMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage rules ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRules {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die External API Call ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_APICall {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_APICall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Url: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_APICall_ApiUrl {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_APICall_ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HTTP Method: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_APICall_Method {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_APICall_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Command: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_Command_Executable {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_Command_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameters: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_Command_Parameter {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_Command_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute Command ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_ExecuteCommand {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_ExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_None {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_Reboot {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake up the machine via WOL ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Action_WOL {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Action_WOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add new rule ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_AddRule {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Boot ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Boot {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom MAC address (e.g. ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_CustomMacAddress {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_CustomMacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Empty Rule&gt; ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_EmptyRule {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_EmptyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while saving the rules: {0}! ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_FailedToSaveRules {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_FailedToSaveRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_General {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete selected rule ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_RemoveRule {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_RemoveRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_RuleDescription {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_RuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rule is enabled ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_RuleIsActive {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_RuleIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_RuleName {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rules: ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Rules {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to cancel? All changes will be lost! ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_SecurityQuestion {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_SecurityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Shutdown {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you really sure you want to delete the rule &quot;{0}&quot;? ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_SureToDeleteRule {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_SureToDeleteRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time (HH:mm): ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Time {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage device rules ähnelt.
        /// </summary>
        public static string strManageDeviceSchedulingRulesDialog_Title {
            get {
                return ResourceManager.GetString("strManageDeviceSchedulingRulesDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Management ähnelt.
        /// </summary>
        public static string strManagment {
            get {
                return ResourceManager.GetString("strManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturer:  ähnelt.
        /// </summary>
        public static string strManufacturer {
            get {
                return ResourceManager.GetString("strManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        public static string strMinutes {
            get {
                return ResourceManager.GetString("strMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motherboard: ähnelt.
        /// </summary>
        public static string strMotherboardDescription {
            get {
                return ResourceManager.GetString("strMotherboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mute Sound ähnelt.
        /// </summary>
        public static string strMuteSound {
            get {
                return ResourceManager.GetString("strMuteSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die n/a ähnelt.
        /// </summary>
        public static string strNA {
            get {
                return ResourceManager.GetString("strNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string strNo {
            get {
                return ResourceManager.GetString("strNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device selected! ähnelt.
        /// </summary>
        public static string strNoDeviceSelected {
            get {
                return ResourceManager.GetString("strNoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No devices found! ähnelt.
        /// </summary>
        public static string strNoDevicesFound {
            get {
                return ResourceManager.GetString("strNoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No warnings! ähnelt.
        /// </summary>
        public static string strNoWarnings {
            get {
                return ResourceManager.GetString("strNoWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive Devices: {0} ähnelt.
        /// </summary>
        public static string strOfflineDevicesTab {
            get {
                return ResourceManager.GetString("strOfflineDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operating System: ähnelt.
        /// </summary>
        public static string strOperatingSystem {
            get {
                return ResourceManager.GetString("strOperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operations ähnelt.
        /// </summary>
        public static string strOperations {
            get {
                return ResourceManager.GetString("strOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        public static string strOsVersion {
            get {
                return ResourceManager.GetString("strOsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network Overview ähnelt.
        /// </summary>
        public static string strOverview {
            get {
                return ResourceManager.GetString("strOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Png Image(*.png)|*.png ähnelt.
        /// </summary>
        public static string strPngFilter {
            get {
                return ResourceManager.GetString("strPngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview: ähnelt.
        /// </summary>
        public static string strPreview {
            get {
                return ResourceManager.GetString("strPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Print Report ähnelt.
        /// </summary>
        public static string strPrintReport {
            get {
                return ResourceManager.GetString("strPrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product:  ähnelt.
        /// </summary>
        public static string strProduct {
            get {
                return ResourceManager.GetString("strProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property ähnelt.
        /// </summary>
        public static string strProperty {
            get {
                return ResourceManager.GetString("strProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Protocol ähnelt.
        /// </summary>
        public static string strProtocol {
            get {
                return ResourceManager.GetString("strProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter valid values! ähnelt.
        /// </summary>
        public static string strProvideValidValues_Message {
            get {
                return ResourceManager.GetString("strProvideValidValues_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid values! ähnelt.
        /// </summary>
        public static string strProvideValidValues_Title {
            get {
                return ResourceManager.GetString("strProvideValidValues_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM: ähnelt.
        /// </summary>
        public static string strRAMDescription {
            get {
                return ResourceManager.GetString("strRAMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ready! ähnelt.
        /// </summary>
        public static string strReady {
            get {
                return ResourceManager.GetString("strReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really? ähnelt.
        /// </summary>
        public static string strReally {
            get {
                return ResourceManager.GetString("strReally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot ähnelt.
        /// </summary>
        public static string strReboot {
            get {
                return ResourceManager.GetString("strReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote Connection ähnelt.
        /// </summary>
        public static string strRemoteConnection {
            get {
                return ResourceManager.GetString("strRemoteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote Shell ähnelt.
        /// </summary>
        public static string strRemoteShell {
            get {
                return ResourceManager.GetString("strRemoteShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report ähnelt.
        /// </summary>
        public static string strReport {
            get {
                return ResourceManager.GetString("strReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery ähnelt.
        /// </summary>
        public static string strReport_Battery {
            get {
                return ResourceManager.GetString("strReport_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available ähnelt.
        /// </summary>
        public static string strReport_BatteryExists {
            get {
                return ResourceManager.GetString("strReport_BatteryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining percent ähnelt.
        /// </summary>
        public static string strReport_BatteryRemaningPercentage {
            get {
                return ResourceManager.GetString("strReport_BatteryRemaningPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIOS ähnelt.
        /// </summary>
        public static string strReport_BIOS {
            get {
                return ResourceManager.GetString("strReport_BIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Built Date ähnelt.
        /// </summary>
        public static string strReport_BuiltDate {
            get {
                return ResourceManager.GetString("strReport_BuiltDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU ähnelt.
        /// </summary>
        public static string strReport_CPU {
            get {
                return ResourceManager.GetString("strReport_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string strReport_Description {
            get {
                return ResourceManager.GetString("strReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device-ID ähnelt.
        /// </summary>
        public static string strReport_DeviceID {
            get {
                return ResourceManager.GetString("strReport_DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Devices Log ähnelt.
        /// </summary>
        public static string strReport_DeviceLog {
            get {
                return ResourceManager.GetString("strReport_DeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device-Type ähnelt.
        /// </summary>
        public static string strReport_DeviceType {
            get {
                return ResourceManager.GetString("strReport_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disk ähnelt.
        /// </summary>
        public static string strReport_Disk {
            get {
                return ResourceManager.GetString("strReport_Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Name ähnelt.
        /// </summary>
        public static string strReport_DiskDeviceName {
            get {
                return ResourceManager.GetString("strReport_DiskDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filesystem ähnelt.
        /// </summary>
        public static string strReport_DiskFilesystem {
            get {
                return ResourceManager.GetString("strReport_DiskFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Space ähnelt.
        /// </summary>
        public static string strReport_DiskFreeSpace {
            get {
                return ResourceManager.GetString("strReport_DiskFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage ähnelt.
        /// </summary>
        public static string strReport_DiskStorage {
            get {
                return ResourceManager.GetString("strReport_DiskStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        public static string strReport_DiskVolumeName {
            get {
                return ResourceManager.GetString("strReport_DiskVolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Domain ähnelt.
        /// </summary>
        public static string strReport_Domain {
            get {
                return ResourceManager.GetString("strReport_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics ähnelt.
        /// </summary>
        public static string strReport_Graphics {
            get {
                return ResourceManager.GetString("strReport_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string strReport_Group {
            get {
                return ResourceManager.GetString("strReport_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardware ähnelt.
        /// </summary>
        public static string strReport_Hardware {
            get {
                return ResourceManager.GetString("strReport_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home.Client-Version ähnelt.
        /// </summary>
        public static string strReport_HomeClientVersion {
            get {
                return ResourceManager.GetString("strReport_HomeClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP-Address ähnelt.
        /// </summary>
        public static string strReport_IPAddress {
            get {
                return ResourceManager.GetString("strReport_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Charging ähnelt.
        /// </summary>
        public static string strReport_IsCharging {
            get {
                return ResourceManager.GetString("strReport_IsCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Primary ähnelt.
        /// </summary>
        public static string strReport_IsPrimary {
            get {
                return ResourceManager.GetString("strReport_IsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string strReport_Location {
            get {
                return ResourceManager.GetString("strReport_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mac Address ähnelt.
        /// </summary>
        public static string strReport_MacAddress {
            get {
                return ResourceManager.GetString("strReport_MacAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motherboard ähnelt.
        /// </summary>
        public static string strReport_Motherboard {
            get {
                return ResourceManager.GetString("strReport_Motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operating System ähnelt.
        /// </summary>
        public static string strReport_OS {
            get {
                return ResourceManager.GetString("strReport_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string strReport_OsName {
            get {
                return ResourceManager.GetString("strReport_OsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product ähnelt.
        /// </summary>
        public static string strReport_Product {
            get {
                return ResourceManager.GetString("strReport_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM ähnelt.
        /// </summary>
        public static string strReport_RAM {
            get {
                return ResourceManager.GetString("strReport_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release Date ähnelt.
        /// </summary>
        public static string strReport_ReleaseDate {
            get {
                return ResourceManager.GetString("strReport_ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
        /// </summary>
        public static string strReport_Resolution {
            get {
                return ResourceManager.GetString("strReport_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Timestamp ähnelt.
        /// </summary>
        public static string strReport_StartTimestamp {
            get {
                return ResourceManager.GetString("strReport_StartTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uptime ähnelt.
        /// </summary>
        public static string strReport_Uptime {
            get {
                return ResourceManager.GetString("strReport_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string strReport_User {
            get {
                return ResourceManager.GetString("strReport_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vendor ähnelt.
        /// </summary>
        public static string strReport_Vendor {
            get {
                return ResourceManager.GetString("strReport_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string strReport_Version {
            get {
                return ResourceManager.GetString("strReport_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string strReport_WarningMessage {
            get {
                return ResourceManager.GetString("strReport_WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning occurred ähnelt.
        /// </summary>
        public static string strReport_WarningOccured {
            get {
                return ResourceManager.GetString("strReport_WarningOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string strReport_Warnings {
            get {
                return ResourceManager.GetString("strReport_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string strReport_WarningType {
            get {
                return ResourceManager.GetString("strReport_WarningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save report ähnelt.
        /// </summary>
        public static string strSaveReport {
            get {
                return ResourceManager.GetString("strSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save HTML ähnelt.
        /// </summary>
        public static string strSaveReportHtml {
            get {
                return ResourceManager.GetString("strSaveReportHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save PDF ähnelt.
        /// </summary>
        public static string strSaveReportPdf {
            get {
                return ResourceManager.GetString("strSaveReportPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screens ähnelt.
        /// </summary>
        public static string strScreens {
            get {
                return ResourceManager.GetString("strScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show screenshot ähnelt.
        /// </summary>
        public static string strScreenshotDialog_ShowScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotDialog_ShowScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acquire new screenshot ähnelt.
        /// </summary>
        public static string strScreenshotViewer_AquireNewScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotViewer_AquireNewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change size ähnelt.
        /// </summary>
        public static string strScreenshotViewer_ChangeSize {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as ... ähnelt.
        /// </summary>
        public static string strScreenshotViewer_SaveAs {
            get {
                return ResourceManager.GetString("strScreenshotViewer_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle LiveView ähnelt.
        /// </summary>
        public static string strScreenshotViewer_ToggleLiveView {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ToggleLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset view ähnelt.
        /// </summary>
        public static string strScreenshotViewer_ViewScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ViewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search: ähnelt.
        /// </summary>
        public static string strSearch {
            get {
                return ResourceManager.GetString("strSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executable: ähnelt.
        /// </summary>
        public static string strSendCommandDialog_App {
            get {
                return ResourceManager.GetString("strSendCommandDialog_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parameter: ähnelt.
        /// </summary>
        public static string strSendCommandDialog_Parameter {
            get {
                return ResourceManager.GetString("strSendCommandDialog_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send command ähnelt.
        /// </summary>
        public static string strSendCommandDialog_Title {
            get {
                return ResourceManager.GetString("strSendCommandDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send Message ähnelt.
        /// </summary>
        public static string strSendMessage {
            get {
                return ResourceManager.GetString("strSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level: ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Error {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Information {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Warning {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content: ähnelt.
        /// </summary>
        public static string strSendMessageDialog_MessageContent {
            get {
                return ResourceManager.GetString("strSendMessageDialog_MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title: ähnelt.
        /// </summary>
        public static string strSendMessageDialog_MessageTitle {
            get {
                return ResourceManager.GetString("strSendMessageDialog_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send message ähnelt.
        /// </summary>
        public static string strSendMessageDialog_Title {
            get {
                return ResourceManager.GetString("strSendMessageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string strSettings {
            get {
                return ResourceManager.GetString("strSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ATTENTION: The API URL must be set, valid and accessible in order to apply the settings! ähnelt.
        /// </summary>
        public static string strSettings_AttentionText {
            get {
                return ResourceManager.GetString("strSettings_AttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test connection ... ähnelt.
        /// </summary>
        public static string strSettings_CheckConnection {
            get {
                return ResourceManager.GetString("strSettings_CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection was successfully established! ähnelt.
        /// </summary>
        public static string strSettings_ConnectionEstablishedSuccuessfully {
            get {
                return ResourceManager.GetString("strSettings_ConnectionEstablishedSuccuessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection could not be established ähnelt.
        /// </summary>
        public static string strSettings_ConnectionNotEstablished {
            get {
                return ResourceManager.GetString("strSettings_ConnectionNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit App ähnelt.
        /// </summary>
        public static string strSettings_ForceExit {
            get {
                return ResourceManager.GetString("strSettings_ForceExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Host Url: (e.g. http://192.168.178.38:83) ähnelt.
        /// </summary>
        public static string strSettings_Host {
            get {
                return ResourceManager.GetString("strSettings_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only continue with a valid connection! Please test your connection to continue! ähnelt.
        /// </summary>
        public static string strSettings_OnlyContinueUsingAValidConnection {
            get {
                return ResourceManager.GetString("strSettings_OnlyContinueUsingAValidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active window glowing effect ähnelt.
        /// </summary>
        public static string strSettingsActivateGlowingEffect {
            get {
                return ResourceManager.GetString("strSettingsActivateGlowingEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show activity ähnelt.
        /// </summary>
        public static string strShowActivity {
            get {
                return ResourceManager.GetString("strShowActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show screens ähnelt.
        /// </summary>
        public static string strShowScreenshots {
            get {
                return ResourceManager.GetString("strShowScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown ähnelt.
        /// </summary>
        public static string strShutdown {
            get {
                return ResourceManager.GetString("strShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown Menu ähnelt.
        /// </summary>
        public static string strShutdownMenu {
            get {
                return ResourceManager.GetString("strShutdownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starting Home.WPF v{0} ... ähnelt.
        /// </summary>
        public static string strStartMessage {
            get {
                return ResourceManager.GetString("strStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free space left: {0} ähnelt.
        /// </summary>
        public static string strStorageWarning_Message {
            get {
                return ResourceManager.GetString("strStorageWarning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success! ähnelt.
        /// </summary>
        public static string strSuccess {
            get {
                return ResourceManager.GetString("strSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The changes have been successfully applied! ähnelt.
        /// </summary>
        public static string strSuccessfullyAppliedChanges {
            get {
                return ResourceManager.GetString("strSuccessfullyAppliedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully cleared the device log! ähnelt.
        /// </summary>
        public static string strSuccessfullyClearedDeviceLog {
            get {
                return ResourceManager.GetString("strSuccessfullyClearedDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully cleared the hardware changes of this device! ähnelt.
        /// </summary>
        public static string strSuccessfullyClearedHardwareLog {
            get {
                return ResourceManager.GetString("strSuccessfullyClearedHardwareLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device was deleted successfully! ähnelt.
        /// </summary>
        public static string strTheDeviceWasDeletedSuccessfully {
            get {
                return ResourceManager.GetString("strTheDeviceWasDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme: ähnelt.
        /// </summary>
        public static string strTheme {
            get {
                return ResourceManager.GetString("strTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        public static string strTo {
            get {
                return ResourceManager.GetString("strTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle Overview ähnelt.
        /// </summary>
        public static string strToggleOverview {
            get {
                return ResourceManager.GetString("strToggleOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle theme ähnelt.
        /// </summary>
        public static string strToggleTheme {
            get {
                return ResourceManager.GetString("strToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        public static string strTools {
            get {
                return ResourceManager.GetString("strTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string strUnkown {
            get {
                return ResourceManager.GetString("strUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string strUser {
            get {
                return ResourceManager.GetString("strUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string strValue {
            get {
                return ResourceManager.GetString("strValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error while sending the WOL request! ähnelt.
        /// </summary>
        public static string strWakeOnLanDialog_FailedToSendWOLRequest {
            get {
                return ResourceManager.GetString("strWakeOnLanDialog_FailedToSendWOLRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid MAC address! ähnelt.
        /// </summary>
        public static string strWakeOnLanDialog_InvalidMac {
            get {
                return ResourceManager.GetString("strWakeOnLanDialog_InvalidMac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake On Lan ähnelt.
        /// </summary>
        public static string strWakeOnLanDialog_Title {
            get {
                return ResourceManager.GetString("strWakeOnLanDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake Up (WOL) ähnelt.
        /// </summary>
        public static string strWakeUp {
            get {
                return ResourceManager.GetString("strWakeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake Up! ähnelt.
        /// </summary>
        public static string strWakeUp_ {
            get {
                return ResourceManager.GetString("strWakeUp_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wake Up Device ähnelt.
        /// </summary>
        public static string strWakeUpDevice {
            get {
                return ResourceManager.GetString("strWakeUpDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string strWarnings {
            get {
                return ResourceManager.GetString("strWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebView2 Runtime couldn&apos;t be created, make sure WebView2 Runtime is installed!
        ///
        ///Download: https://developer.microsoft.com/en-us/microsoft-edge/webview2/ ähnelt.
        /// </summary>
        public static string strWebView2RuntimeNotFound_Message {
            get {
                return ResourceManager.GetString("strWebView2RuntimeNotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WebView2 Runtime not found! ähnelt.
        /// </summary>
        public static string strWebView2RuntimeNotFound_Title {
            get {
                return ResourceManager.GetString("strWebView2RuntimeNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Magic packet could not be sent: {0}! ähnelt.
        /// </summary>
        public static string strWOL_MagickPackageSendError {
            get {
                return ResourceManager.GetString("strWOL_MagickPackageSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Magic Packet has been successfully sent! ähnelt.
        /// </summary>
        public static string strWOL_SuccessfullySentPackage {
            get {
                return ResourceManager.GetString("strWOL_SuccessfullySentPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This device has not reported a mac address, therefore Wake On LAN is currently not possible! ähnelt.
        /// </summary>
        public static string strWOLNotPossible {
            get {
                return ResourceManager.GetString("strWOLNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string strYes {
            get {
                return ResourceManager.GetString("strYes", resourceCulture);
            }
        }
    }
}
