//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Home.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string strAbout {
            get {
                return ResourceManager.GetString("strAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Concept and realisation by Andreas L. ähnelt.
        /// </summary>
        public static string strAbout_Line1 {
            get {
                return ResourceManager.GetString("strAbout_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Many thanks ... ähnelt.
        /// </summary>
        public static string strAbout_Line2 {
            get {
                return ResourceManager.GetString("strAbout_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... to ähnelt.
        /// </summary>
        public static string strAboutTextFluentRibbon_1 {
            get {
                return ResourceManager.GetString("strAboutTextFluentRibbon_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for the menu! ähnelt.
        /// </summary>
        public static string strAboutTextFluentRibbon_2 {
            get {
                return ResourceManager.GetString("strAboutTextFluentRibbon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ... to ähnelt.
        /// </summary>
        public static string strAboutTextIcons8_1 {
            get {
                return ResourceManager.GetString("strAboutTextIcons8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die for the free icons! ähnelt.
        /// </summary>
        public static string strAboutTextIcons8_2 {
            get {
                return ResourceManager.GetString("strAboutTextIcons8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active Devices: {0} ähnelt.
        /// </summary>
        public static string strActiveDevicesTab {
            get {
                return ResourceManager.GetString("strActiveDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activity ähnelt.
        /// </summary>
        public static string strActivity {
            get {
                return ResourceManager.GetString("strActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All ähnelt.
        /// </summary>
        public static string strAll {
            get {
                return ResourceManager.GetString("strAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AllDevices: {0} ähnelt.
        /// </summary>
        public static string strAllDevicesTab {
            get {
                return ResourceManager.GetString("strAllDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Android device cannot be shutdown or restarted! ähnelt.
        /// </summary>
        public static string strAndroidDeviceNoShutdownSupport {
            get {
                return ResourceManager.GetString("strAndroidDeviceNoShutdownSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sure? ähnelt.
        /// </summary>
        public static string strAreYouSure {
            get {
                return ResourceManager.GetString("strAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to delete the device {0}? ähnelt.
        /// </summary>
        public static string strAreYouSureToDeleteDevice {
            get {
                return ResourceManager.GetString("strAreYouSureToDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery: ähnelt.
        /// </summary>
        public static string strBattery {
            get {
                return ResourceManager.GetString("strBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bit ähnelt.
        /// </summary>
        public static string strBit {
            get {
                return ResourceManager.GetString("strBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charging ähnelt.
        /// </summary>
        public static string strCharging {
            get {
                return ResourceManager.GetString("strCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear Log ähnelt.
        /// </summary>
        public static string strClearLog {
            get {
                return ResourceManager.GetString("strClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cores ähnelt.
        /// </summary>
        public static string strCores {
            get {
                return ResourceManager.GetString("strCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU: ähnelt.
        /// </summary>
        public static string strCPUDescription {
            get {
                return ResourceManager.GetString("strCPUDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string strDark {
            get {
                return ResourceManager.GetString("strDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color mode: ähnelt.
        /// </summary>
        public static string strDarkModeSettingsTitle {
            get {
                return ResourceManager.GetString("strDarkModeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM/dd/yyyy ähnelt.
        /// </summary>
        public static string strDateFormat {
            get {
                return ResourceManager.GetString("strDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MM/dd/yyyy HH:mm ähnelt.
        /// </summary>
        public static string strDateTimeFormat {
            get {
                return ResourceManager.GetString("strDateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Days ähnelt.
        /// </summary>
        public static string strDays {
            get {
                return ResourceManager.GetString("strDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Device ähnelt.
        /// </summary>
        public static string strDeleteDevice {
            get {
                return ResourceManager.GetString("strDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device ähnelt.
        /// </summary>
        public static string strDevice {
            get {
                return ResourceManager.GetString("strDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The unit is offline - switching to live mode is not possible! ähnelt.
        /// </summary>
        public static string strDeviceCannotSwitchToLiveMode {
            get {
                return ResourceManager.GetString("strDeviceCannotSwitchToLiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardware Protocol ähnelt.
        /// </summary>
        public static string strDeviceChanges {
            get {
                return ResourceManager.GetString("strDeviceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client-Version:  ähnelt.
        /// </summary>
        public static string strDeviceClientVersion {
            get {
                return ResourceManager.GetString("strDeviceClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description:  ähnelt.
        /// </summary>
        public static string strDeviceDescription {
            get {
                return ResourceManager.GetString("strDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not associated ähnelt.
        /// </summary>
        public static string strDeviceLocationNotAssigend {
            get {
                return ResourceManager.GetString("strDeviceLocationNotAssigend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Log ähnelt.
        /// </summary>
        public static string strDeviceLog {
            get {
                return ResourceManager.GetString("strDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This device is currently offline! No operations can be executed! ähnelt.
        /// </summary>
        public static string strDeviceOfflineCannotExecuteCommand {
            get {
                return ResourceManager.GetString("strDeviceOfflineCannotExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uptime:  ähnelt.
        /// </summary>
        public static string strDeviceOnlineTime {
            get {
                return ResourceManager.GetString("strDeviceOnlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start:  ähnelt.
        /// </summary>
        public static string strDeviceStart {
            get {
                return ResourceManager.GetString("strDeviceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISKs ähnelt.
        /// </summary>
        public static string strDisk {
            get {
                return ResourceManager.GetString("strDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to restart the machine {0}? ähnelt.
        /// </summary>
        public static string strDoYouReallyWantToRestartDevice {
            get {
                return ResourceManager.GetString("strDoYouReallyWantToRestartDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure you want to shutdown the machine {0}? ähnelt.
        /// </summary>
        public static string strDoYouReallyWantToShutdownDevice {
            get {
                return ResourceManager.GetString("strDoYouReallyWantToShutdownDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error! ähnelt.
        /// </summary>
        public static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute Command ähnelt.
        /// </summary>
        public static string strExecuteCommand {
            get {
                return ResourceManager.GetString("strExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to clear device log: {0} ähnelt.
        /// </summary>
        public static string strFailedToClearDeviceLog {
            get {
                return ResourceManager.GetString("strFailedToClearDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to save the report! ähnelt.
        /// </summary>
        public static string strFailedToSaveReport {
            get {
                return ResourceManager.GetString("strFailedToSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error saving the image: {0} ähnelt.
        /// </summary>
        public static string strFailedToSaveScreenshotAsImage {
            get {
                return ResourceManager.GetString("strFailedToSaveScreenshotAsImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This feature is currently only supported on newer Windows systems (Windows 7 SP1 or newer) or on Linux Systems! ähnelt.
        /// </summary>
        public static string strFeatureIsNotSupportedOnSelectedDevice {
            get {
                return ResourceManager.GetString("strFeatureIsNotSupportedOnSelectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string strFile {
            get {
                return ResourceManager.GetString("strFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date Of Change ähnelt.
        /// </summary>
        public static string strFileExplorerDateOfChange {
            get {
                return ResourceManager.GetString("strFileExplorerDateOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete file ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DeleteFile {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete folder ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DeleteFolder {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download file ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DownloadFile {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download folder as ZIP-File ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_DownloadFolderAsZIP {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DownloadFolderAsZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Properties ähnelt.
        /// </summary>
        public static string strFileExplorerMenu_Properties {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string strFileExplorerName {
            get {
                return ResourceManager.GetString("strFileExplorerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size ähnelt.
        /// </summary>
        public static string strFileExplorerSize {
            get {
                return ResourceManager.GetString("strFileExplorerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string strFileExplorerType {
            get {
                return ResourceManager.GetString("strFileExplorerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder ähnelt.
        /// </summary>
        public static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics: ähnelt.
        /// </summary>
        public static string strGraphicsDescription {
            get {
                return ResourceManager.GetString("strGraphicsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die free of ähnelt.
        /// </summary>
        public static string strHDD_FreeOf {
            get {
                return ResourceManager.GetString("strHDD_FreeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        public static string strHours {
            get {
                return ResourceManager.GetString("strHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Individual Overview ähnelt.
        /// </summary>
        public static string strIndividualOverview {
            get {
                return ResourceManager.GetString("strIndividualOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show accent color in titlebar ähnelt.
        /// </summary>
        public static string strIsColorfulTheme {
            get {
                return ResourceManager.GetString("strIsColorfulTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die en ähnelt.
        /// </summary>
        public static string strLang {
            get {
                return ResourceManager.GetString("strLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string strLight {
            get {
                return ResourceManager.GetString("strLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location:  ähnelt.
        /// </summary>
        public static string strLocation {
            get {
                return ResourceManager.GetString("strLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Managment ähnelt.
        /// </summary>
        public static string strManagment {
            get {
                return ResourceManager.GetString("strManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturer:  ähnelt.
        /// </summary>
        public static string strManufacturer {
            get {
                return ResourceManager.GetString("strManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minutes ähnelt.
        /// </summary>
        public static string strMinutes {
            get {
                return ResourceManager.GetString("strMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motherboard: ähnelt.
        /// </summary>
        public static string strMotherboardDescription {
            get {
                return ResourceManager.GetString("strMotherboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mute Sound ähnelt.
        /// </summary>
        public static string strMuteSound {
            get {
                return ResourceManager.GetString("strMuteSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string strNo {
            get {
                return ResourceManager.GetString("strNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device selected! ähnelt.
        /// </summary>
        public static string strNoDeviceSelected {
            get {
                return ResourceManager.GetString("strNoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No warnings! ähnelt.
        /// </summary>
        public static string strNoWarnings {
            get {
                return ResourceManager.GetString("strNoWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inactive Devices: {0} ähnelt.
        /// </summary>
        public static string strOfflineDevicesTab {
            get {
                return ResourceManager.GetString("strOfflineDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operating System: ähnelt.
        /// </summary>
        public static string strOperatingSystem {
            get {
                return ResourceManager.GetString("strOperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version: ähnelt.
        /// </summary>
        public static string strOsVersion {
            get {
                return ResourceManager.GetString("strOsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Network Overview ähnelt.
        /// </summary>
        public static string strOverview {
            get {
                return ResourceManager.GetString("strOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Png Image(*.png)|*.png ähnelt.
        /// </summary>
        public static string strPngFilter {
            get {
                return ResourceManager.GetString("strPngFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product:  ähnelt.
        /// </summary>
        public static string strProduct {
            get {
                return ResourceManager.GetString("strProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Property ähnelt.
        /// </summary>
        public static string strProperty {
            get {
                return ResourceManager.GetString("strProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM: ähnelt.
        /// </summary>
        public static string strRAMDescription {
            get {
                return ResourceManager.GetString("strRAMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reboot ähnelt.
        /// </summary>
        public static string strReboot {
            get {
                return ResourceManager.GetString("strReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote Connection ähnelt.
        /// </summary>
        public static string strRemoteConnection {
            get {
                return ResourceManager.GetString("strRemoteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote Shell ähnelt.
        /// </summary>
        public static string strRemoteShell {
            get {
                return ResourceManager.GetString("strRemoteShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Report ähnelt.
        /// </summary>
        public static string strReport {
            get {
                return ResourceManager.GetString("strReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Battery ähnelt.
        /// </summary>
        public static string strReport_Battery {
            get {
                return ResourceManager.GetString("strReport_Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Available ähnelt.
        /// </summary>
        public static string strReport_BatteryExists {
            get {
                return ResourceManager.GetString("strReport_BatteryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remaining percent ähnelt.
        /// </summary>
        public static string strReport_BatteryRemaningPercentage {
            get {
                return ResourceManager.GetString("strReport_BatteryRemaningPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Built Date ähnelt.
        /// </summary>
        public static string strReport_BuiltDate {
            get {
                return ResourceManager.GetString("strReport_BuiltDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU ähnelt.
        /// </summary>
        public static string strReport_CPU {
            get {
                return ResourceManager.GetString("strReport_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string strReport_Description {
            get {
                return ResourceManager.GetString("strReport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device-ID ähnelt.
        /// </summary>
        public static string strReport_DeviceID {
            get {
                return ResourceManager.GetString("strReport_DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Devices Log ähnelt.
        /// </summary>
        public static string strReport_DeviceLog {
            get {
                return ResourceManager.GetString("strReport_DeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device-Type ähnelt.
        /// </summary>
        public static string strReport_DeviceType {
            get {
                return ResourceManager.GetString("strReport_DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disk ähnelt.
        /// </summary>
        public static string strReport_Disk {
            get {
                return ResourceManager.GetString("strReport_Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Name ähnelt.
        /// </summary>
        public static string strReport_DiskDeviceName {
            get {
                return ResourceManager.GetString("strReport_DiskDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filesystem ähnelt.
        /// </summary>
        public static string strReport_DiskFilesystem {
            get {
                return ResourceManager.GetString("strReport_DiskFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Space ähnelt.
        /// </summary>
        public static string strReport_DiskFreeSpace {
            get {
                return ResourceManager.GetString("strReport_DiskFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Storage ähnelt.
        /// </summary>
        public static string strReport_DiskStorage {
            get {
                return ResourceManager.GetString("strReport_DiskStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume ähnelt.
        /// </summary>
        public static string strReport_DiskVolumeName {
            get {
                return ResourceManager.GetString("strReport_DiskVolumeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Domain ähnelt.
        /// </summary>
        public static string strReport_Domain {
            get {
                return ResourceManager.GetString("strReport_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics ähnelt.
        /// </summary>
        public static string strReport_Graphics {
            get {
                return ResourceManager.GetString("strReport_Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group ähnelt.
        /// </summary>
        public static string strReport_Group {
            get {
                return ResourceManager.GetString("strReport_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hardware ähnelt.
        /// </summary>
        public static string strReport_Hardware {
            get {
                return ResourceManager.GetString("strReport_Hardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home.Client-Version ähnelt.
        /// </summary>
        public static string strReport_HomeClientVersion {
            get {
                return ResourceManager.GetString("strReport_HomeClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP-Address ähnelt.
        /// </summary>
        public static string strReport_IPAddress {
            get {
                return ResourceManager.GetString("strReport_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Charging ähnelt.
        /// </summary>
        public static string strReport_IsCharging {
            get {
                return ResourceManager.GetString("strReport_IsCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Primary ähnelt.
        /// </summary>
        public static string strReport_IsPrimary {
            get {
                return ResourceManager.GetString("strReport_IsPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string strReport_Location {
            get {
                return ResourceManager.GetString("strReport_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motherboard ähnelt.
        /// </summary>
        public static string strReport_Motherboard {
            get {
                return ResourceManager.GetString("strReport_Motherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operating System ähnelt.
        /// </summary>
        public static string strReport_OS {
            get {
                return ResourceManager.GetString("strReport_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string strReport_OsName {
            get {
                return ResourceManager.GetString("strReport_OsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Product ähnelt.
        /// </summary>
        public static string strReport_Product {
            get {
                return ResourceManager.GetString("strReport_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RAM ähnelt.
        /// </summary>
        public static string strReport_RAM {
            get {
                return ResourceManager.GetString("strReport_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
        /// </summary>
        public static string strReport_Resolution {
            get {
                return ResourceManager.GetString("strReport_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Timestamp ähnelt.
        /// </summary>
        public static string strReport_StartTimestamp {
            get {
                return ResourceManager.GetString("strReport_StartTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uptime ähnelt.
        /// </summary>
        public static string strReport_Uptime {
            get {
                return ResourceManager.GetString("strReport_Uptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string strReport_User {
            get {
                return ResourceManager.GetString("strReport_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vendor ähnelt.
        /// </summary>
        public static string strReport_Vendor {
            get {
                return ResourceManager.GetString("strReport_Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string strReport_Version {
            get {
                return ResourceManager.GetString("strReport_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string strReport_WarningMessage {
            get {
                return ResourceManager.GetString("strReport_WarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning occured ähnelt.
        /// </summary>
        public static string strReport_WarningOccured {
            get {
                return ResourceManager.GetString("strReport_WarningOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warnings ähnelt.
        /// </summary>
        public static string strReport_Warnings {
            get {
                return ResourceManager.GetString("strReport_Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string strReport_WarningType {
            get {
                return ResourceManager.GetString("strReport_WarningType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save report ähnelt.
        /// </summary>
        public static string strSaveReport {
            get {
                return ResourceManager.GetString("strSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Screens ähnelt.
        /// </summary>
        public static string strScreens {
            get {
                return ResourceManager.GetString("strScreens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show screenshot ähnelt.
        /// </summary>
        public static string strScreenshotDialog_ShowScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotDialog_ShowScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aquire new screenshot ähnelt.
        /// </summary>
        public static string strScreenshotViewer_AquireNewScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotViewer_AquireNewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change size ähnelt.
        /// </summary>
        public static string strScreenshotViewer_ChangeSize {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as ... ähnelt.
        /// </summary>
        public static string strScreenshotViewer_SaveAs {
            get {
                return ResourceManager.GetString("strScreenshotViewer_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle LiveView ähnelt.
        /// </summary>
        public static string strScreenshotViewer_ToggleLiveView {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ToggleLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset view ähnelt.
        /// </summary>
        public static string strScreenshotViewer_ViewScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ViewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App: ähnelt.
        /// </summary>
        public static string strSendCommandDialog_App {
            get {
                return ResourceManager.GetString("strSendCommandDialog_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paramter: ähnelt.
        /// </summary>
        public static string strSendCommandDialog_Parameter {
            get {
                return ResourceManager.GetString("strSendCommandDialog_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send command ähnelt.
        /// </summary>
        public static string strSendCommandDialog_Title {
            get {
                return ResourceManager.GetString("strSendCommandDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send Message ähnelt.
        /// </summary>
        public static string strSendMessage {
            get {
                return ResourceManager.GetString("strSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Level: ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Error {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Information {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning ähnelt.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Warning {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content: ähnelt.
        /// </summary>
        public static string strSendMessageDialog_MessageContent {
            get {
                return ResourceManager.GetString("strSendMessageDialog_MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title: ähnelt.
        /// </summary>
        public static string strSendMessageDialog_MessageTitle {
            get {
                return ResourceManager.GetString("strSendMessageDialog_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Send message ähnelt.
        /// </summary>
        public static string strSendMessageDialog_Title {
            get {
                return ResourceManager.GetString("strSendMessageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string strSettings {
            get {
                return ResourceManager.GetString("strSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ATTENTION: The API URL must be set, valid and accessible in order to apply the settings! ähnelt.
        /// </summary>
        public static string strSettings_AttentionText {
            get {
                return ResourceManager.GetString("strSettings_AttentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test connection ... ähnelt.
        /// </summary>
        public static string strSettings_CheckConnection {
            get {
                return ResourceManager.GetString("strSettings_CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection was successfully established! ähnelt.
        /// </summary>
        public static string strSettings_ConnectionEstablishedSuccuessfully {
            get {
                return ResourceManager.GetString("strSettings_ConnectionEstablishedSuccuessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection could not be established ähnelt.
        /// </summary>
        public static string strSettings_ConnectionNotEstablished {
            get {
                return ResourceManager.GetString("strSettings_ConnectionNotEstablished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit App ähnelt.
        /// </summary>
        public static string strSettings_ForceExit {
            get {
                return ResourceManager.GetString("strSettings_ForceExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Host Url: (e.g. http://192.168.178.38:83) ähnelt.
        /// </summary>
        public static string strSettings_Host {
            get {
                return ResourceManager.GetString("strSettings_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can only continue with a valid connection! Please test your connection to continue! ähnelt.
        /// </summary>
        public static string strSettings_OnlyContinueUsingAValidConnection {
            get {
                return ResourceManager.GetString("strSettings_OnlyContinueUsingAValidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Active window glowing effect ähnelt.
        /// </summary>
        public static string strSettingsActivateGlowingEffect {
            get {
                return ResourceManager.GetString("strSettingsActivateGlowingEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show screenshots ähnelt.
        /// </summary>
        public static string strShowScreenshots {
            get {
                return ResourceManager.GetString("strShowScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown ähnelt.
        /// </summary>
        public static string strShutdown {
            get {
                return ResourceManager.GetString("strShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shutdown Menu ähnelt.
        /// </summary>
        public static string strShutdownMenu {
            get {
                return ResourceManager.GetString("strShutdownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Success! ähnelt.
        /// </summary>
        public static string strSuccess {
            get {
                return ResourceManager.GetString("strSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully cleared the device log! ähnelt.
        /// </summary>
        public static string strSuccessfullyClearedDeviceLog {
            get {
                return ResourceManager.GetString("strSuccessfullyClearedDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device was deleted successfully! ähnelt.
        /// </summary>
        public static string strTheDeviceWasDeletedSuccessfully {
            get {
                return ResourceManager.GetString("strTheDeviceWasDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme: ähnelt.
        /// </summary>
        public static string strTheme {
            get {
                return ResourceManager.GetString("strTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die to ähnelt.
        /// </summary>
        public static string strTo {
            get {
                return ResourceManager.GetString("strTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toggle theme ähnelt.
        /// </summary>
        public static string strToggleTheme {
            get {
                return ResourceManager.GetString("strToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tools ähnelt.
        /// </summary>
        public static string strTools {
            get {
                return ResourceManager.GetString("strTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown ähnelt.
        /// </summary>
        public static string strUnkown {
            get {
                return ResourceManager.GetString("strUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string strUser {
            get {
                return ResourceManager.GetString("strUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Value ähnelt.
        /// </summary>
        public static string strValue {
            get {
                return ResourceManager.GetString("strValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string strYes {
            get {
                return ResourceManager.GetString("strYes", resourceCulture);
            }
        }
    }
}
