//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Devices: {0}.
        /// </summary>
        public static string strActiveDevicesTab {
            get {
                return ResourceManager.GetString("strActiveDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        public static string strActivity {
            get {
                return ResourceManager.GetString("strActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllDevices: {0}.
        /// </summary>
        public static string strAllDevicesTab {
            get {
                return ResourceManager.GetString("strAllDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string strClearLog {
            get {
                return ResourceManager.GetString("strClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Device.
        /// </summary>
        public static string strDeleteDevice {
            get {
                return ResourceManager.GetString("strDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string strDevice {
            get {
                return ResourceManager.GetString("strDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client-Version: .
        /// </summary>
        public static string strDeviceClientVersion {
            get {
                return ResourceManager.GetString("strDeviceClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description: .
        /// </summary>
        public static string strDeviceDescription {
            get {
                return ResourceManager.GetString("strDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht zugeordnet.
        /// </summary>
        public static string strDeviceLocationNotAssigend {
            get {
                return ResourceManager.GetString("strDeviceLocationNotAssigend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Log.
        /// </summary>
        public static string strDeviceLog {
            get {
                return ResourceManager.GetString("strDeviceLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uptime: .
        /// </summary>
        public static string strDeviceOnlineTime {
            get {
                return ResourceManager.GetString("strDeviceOnlineTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start: .
        /// </summary>
        public static string strDeviceStart {
            get {
                return ResourceManager.GetString("strDeviceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISKs.
        /// </summary>
        public static string strDisk {
            get {
                return ResourceManager.GetString("strDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Command.
        /// </summary>
        public static string strExecuteCommand {
            get {
                return ResourceManager.GetString("strExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string strExit {
            get {
                return ResourceManager.GetString("strExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string strFile {
            get {
                return ResourceManager.GetString("strFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Change.
        /// </summary>
        public static string strFileExplorerDateOfChange {
            get {
                return ResourceManager.GetString("strFileExplorerDateOfChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string strFileExplorerMenu_DeleteFile {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete folder.
        /// </summary>
        public static string strFileExplorerMenu_DeleteFolder {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        public static string strFileExplorerMenu_DownloadFile {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download folder as ZIP-File.
        /// </summary>
        public static string strFileExplorerMenu_DownloadFolderAsZIP {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_DownloadFolderAsZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string strFileExplorerMenu_Properties {
            get {
                return ResourceManager.GetString("strFileExplorerMenu_Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string strFileExplorerName {
            get {
                return ResourceManager.GetString("strFileExplorerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string strFileExplorerSize {
            get {
                return ResourceManager.GetString("strFileExplorerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string strFileExplorerType {
            get {
                return ResourceManager.GetString("strFileExplorerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string strFolder {
            get {
                return ResourceManager.GetString("strFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string strGeneral {
            get {
                return ResourceManager.GetString("strGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free of.
        /// </summary>
        public static string strHDD_FreeOf {
            get {
                return ResourceManager.GetString("strHDD_FreeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual Overview.
        /// </summary>
        public static string strIndividualOverview {
            get {
                return ResourceManager.GetString("strIndividualOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        public static string strLocation {
            get {
                return ResourceManager.GetString("strLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managment.
        /// </summary>
        public static string strManagment {
            get {
                return ResourceManager.GetString("strManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer: .
        /// </summary>
        public static string strManufacturer {
            get {
                return ResourceManager.GetString("strManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute Sound.
        /// </summary>
        public static string strMuteSound {
            get {
                return ResourceManager.GetString("strMuteSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No device selected!.
        /// </summary>
        public static string strNoDeviceSelected {
            get {
                return ResourceManager.GetString("strNoDeviceSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Devices: {0}.
        /// </summary>
        public static string strOfflineDevicesTab {
            get {
                return ResourceManager.GetString("strOfflineDevicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string strOK {
            get {
                return ResourceManager.GetString("strOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Overview.
        /// </summary>
        public static string strOverview {
            get {
                return ResourceManager.GetString("strOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product: .
        /// </summary>
        public static string strProduct {
            get {
                return ResourceManager.GetString("strProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string strReboot {
            get {
                return ResourceManager.GetString("strReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Connection.
        /// </summary>
        public static string strRemoteConnection {
            get {
                return ResourceManager.GetString("strRemoteConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Shell.
        /// </summary>
        public static string strRemoteShell {
            get {
                return ResourceManager.GetString("strRemoteShell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show screenshot.
        /// </summary>
        public static string strScreenshotDialog_ShowScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotDialog_ShowScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aquire new screenshot.
        /// </summary>
        public static string strScreenshotViewer_AquireNewScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotViewer_AquireNewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change size.
        /// </summary>
        public static string strScreenshotViewer_ChangeSize {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ChangeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as ....
        /// </summary>
        public static string strScreenshotViewer_SaveAs {
            get {
                return ResourceManager.GetString("strScreenshotViewer_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle LiveView.
        /// </summary>
        public static string strScreenshotViewer_ToggleLiveView {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ToggleLiveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset view.
        /// </summary>
        public static string strScreenshotViewer_ViewScreenshot {
            get {
                return ResourceManager.GetString("strScreenshotViewer_ViewScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App:.
        /// </summary>
        public static string strSendCommandDialog_App {
            get {
                return ResourceManager.GetString("strSendCommandDialog_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramter:.
        /// </summary>
        public static string strSendCommandDialog_Parameter {
            get {
                return ResourceManager.GetString("strSendCommandDialog_Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send command.
        /// </summary>
        public static string strSendCommandDialog_Title {
            get {
                return ResourceManager.GetString("strSendCommandDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string strSendMessage {
            get {
                return ResourceManager.GetString("strSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string strSendMessageDialog_LogLevel {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Error {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Information {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string strSendMessageDialog_LogLevel_Warning {
            get {
                return ResourceManager.GetString("strSendMessageDialog_LogLevel_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content:.
        /// </summary>
        public static string strSendMessageDialog_MessageContent {
            get {
                return ResourceManager.GetString("strSendMessageDialog_MessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string strSendMessageDialog_MessageTitle {
            get {
                return ResourceManager.GetString("strSendMessageDialog_MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send message.
        /// </summary>
        public static string strSendMessageDialog_Title {
            get {
                return ResourceManager.GetString("strSendMessageDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show screenshots.
        /// </summary>
        public static string strShowScreenshots {
            get {
                return ResourceManager.GetString("strShowScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        public static string strShutdown {
            get {
                return ResourceManager.GetString("strShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown Menu.
        /// </summary>
        public static string strShutdownMenu {
            get {
                return ResourceManager.GetString("strShutdownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string strTo {
            get {
                return ResourceManager.GetString("strTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle theme.
        /// </summary>
        public static string strToggleTheme {
            get {
                return ResourceManager.GetString("strToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string strTools {
            get {
                return ResourceManager.GetString("strTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string strUnkown {
            get {
                return ResourceManager.GetString("strUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string strUser {
            get {
                return ResourceManager.GetString("strUser", resourceCulture);
            }
        }
    }
}
