//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home.Service.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Home.Service.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow remote access to the file system ähnelt.
        /// </summary>
        public static string strAllowRemoteFileAccess {
            get {
                return ResourceManager.GetString("strAllowRemoteFileAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Url ähnelt.
        /// </summary>
        public static string strAPIUrl {
            get {
                return ResourceManager.GetString("strAPIUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device ähnelt.
        /// </summary>
        public static string strDevice {
            get {
                return ResourceManager.GetString("strDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Group: ähnelt.
        /// </summary>
        public static string strDeviceGroup {
            get {
                return ResourceManager.GetString("strDeviceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;Not yet registered&gt; ähnelt.
        /// </summary>
        public static string strDeviceNotYetRegistered {
            get {
                return ResourceManager.GetString("strDeviceNotYetRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Settings ähnelt.
        /// </summary>
        public static string strDeviceSettings {
            get {
                return ResourceManager.GetString("strDeviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device Type: ähnelt.
        /// </summary>
        public static string strDeviceType {
            get {
                return ResourceManager.GetString("strDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use ID from previous device (migration) ähnelt.
        /// </summary>
        public static string strEditID {
            get {
                return ResourceManager.GetString("strEditID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable automatic search for updates ähnelt.
        /// </summary>
        public static string strEnableAutomaticUpdateSearch {
            get {
                return ResourceManager.GetString("strEnableAutomaticUpdateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable Screenshots ähnelt.
        /// </summary>
        public static string strEnableScreenshots {
            get {
                return ResourceManager.GetString("strEnableScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string strError {
            get {
                return ResourceManager.GetString("strError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to setup autostart: {0} ähnelt.
        /// </summary>
        public static string strFailedToSetupAutostart {
            get {
                return ResourceManager.GetString("strFailedToSetupAutostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More settings ähnelt.
        /// </summary>
        public static string strFurtherSettings {
            get {
                return ResourceManager.GetString("strFurtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set WshShell = CreateObject(&quot;WScript.Shell&quot; ) 
        ///WshShell.Run &quot;&quot;&quot;{0}&quot;&quot;&quot;, 0
        ///Set WshShell = Nothing ähnelt.
        /// </summary>
        public static string strHomeVBSStartupFile {
            get {
                return ResourceManager.GetString("strHomeVBSStartupFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hours ähnelt.
        /// </summary>
        public static string strHours {
            get {
                return ResourceManager.GetString("strHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID (Guid): ähnelt.
        /// </summary>
        public static string strIDLabel {
            get {
                return ResourceManager.GetString("strIDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initialize ähnelt.
        /// </summary>
        public static string strInitalize {
            get {
                return ResourceManager.GetString("strInitalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid data set! ähnelt.
        /// </summary>
        public static string strInvalidDataSet {
            get {
                return ResourceManager.GetString("strInvalidDataSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location: ähnelt.
        /// </summary>
        public static string strLocation {
            get {
                return ResourceManager.GetString("strLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operating System: ähnelt.
        /// </summary>
        public static string strOS {
            get {
                return ResourceManager.GetString("strOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save and Start ähnelt.
        /// </summary>
        public static string strSaveAndClose {
            get {
                return ResourceManager.GetString("strSaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install updates at startup (if available) ähnelt.
        /// </summary>
        public static string strSearchForUpdatesOnStart {
            get {
                return ResourceManager.GetString("strSearchForUpdatesOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup autostart ähnelt.
        /// </summary>
        public static string strSetupAutostart {
            get {
                return ResourceManager.GetString("strSetupAutostart", resourceCulture);
            }
        }
    }
}
