// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models
{
    public partial class DeviceCommand
    {
        public int DeviceCommandId { get; set; }
        public int? DeviceId { get; set; }
        public string Executable { get; set; }
        public string Paramter { get; set; }
        public DateTime Timestamp { get; set; }
        public bool IsExceuted { get; set; }

        public virtual Device Device { get; set; }
    }
}