// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models;

public partial class DeviceBattery
{
    public int BatteryId { get; set; }

    public bool IsCharging { get; set; }

    public double? Percentage { get; set; }

    public virtual ICollection<DeviceEnvironment> DeviceEnvironment { get; set; } = new List<DeviceEnvironment>();
}