// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models
{
    public partial class DeviceWarning
    {
        public int WarningId { get; set; }
        public int? DeviceId { get; set; }
        public short WarningType { get; set; }
        public long CriticalValue { get; set; }
        public string AdditionalInfo { get; set; }
        public DateTime Timestamp { get; set; }

        public virtual Device Device { get; set; }
    }
}