// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models;

public partial class DeviceType
{
    public int TypeId { get; set; }

    public string Type { get; set; }

    public virtual ICollection<Device> Device { get; set; } = new List<Device>();
}