// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models;

public partial class DeviceBios
{
    public int Id { get; set; }

    public int DeviceId { get; set; }

    public string Vendor { get; set; }

    public string Description { get; set; }

    public string Version { get; set; }

    public DateTime? ReleaseDate { get; set; }

    public virtual Device Device { get; set; }
}