// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models;

public partial class DeviceEnvironment
{
    public int DeviceId { get; set; }

    public string Product { get; set; }

    public string Description { get; set; }

    public string Vendor { get; set; }

    public string Osname { get; set; }

    public string Osversion { get; set; }

    public string Cpuname { get; set; }

    public short? Cpucount { get; set; }

    public double? Cpuusage { get; set; }

    public string Motherboard { get; set; }

    public double? TotalRam { get; set; }

    public double? AvailableRam { get; set; }

    public double? DiskUsage { get; set; }

    public bool Is64BitOs { get; set; }

    public string MachineName { get; set; }

    public string UserName { get; set; }

    public string DomainName { get; set; }

    public long? RunningTime { get; set; }

    public DateTime? StartTimestamp { get; set; }

    public int? BatteryId { get; set; }

    public virtual DeviceBattery Battery { get; set; }

    public virtual Device Device { get; set; }
}