// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Home.API.home.Models
{
    public partial class DeviceLog
    {
        public int LogEntryId { get; set; }
        public int DeviceId { get; set; }
        public string Blob { get; set; }
        public DateTime? Timestamp { get; set; }
        public int LogLevel { get; set; }

        public virtual Device Device { get; set; }
    }
}